build:
  environment:
    php: 8.0.0

  nodes:
    analysis:
      tests:
        override:
        - php-scrutinizer-run
        - phpcs-run

#    tests-and-coverage:
#      tests:
#        override:
#        - command: 'php ./vendor/bin/phpunit --coverage-clover=clover.xml'
#          coverage:
#            file: clover.xml
#            format: clover

filter:
  paths:
  - src/

  excluded_paths:
  - tests/
  - bin/
