language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0snapshot

 matrix:
  allow_failures:
    - php: 8.0snapshot

addons:
  apt:
    packages:
    - libevent-dev

cache:
  bundler: true

notifications:
  email: false

install:
  - travis_retry ./.travis/travis-init.sh
  - travis_retry composer install --no-interaction --prefer-source

script:
  vendor/bin/phpunit --coverage-text
 
