version: '3.7'

services:
  &app-service app:
    # https://github.com/alecrabbit/docker-php73-cli-alpine
    image: dralec/php80-cli-alpine
    hostname: *app-service
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}" # Set variables in .env file
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ./:/var/www
    environment:
      DOCKER_TERM: "${TERM:-}"      # pass host $TERM variable
      COLORTERM: "${COLORTERM:-}"   # pass host $COLORTERM variable
    command: keep-alive.sh
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
