name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [7.4]
        dependency-version: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug

#      - name: Setup Problem Matches
#        run: |
#          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
#          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

#      - name: Run test suite
#        run: composer run-script test

      - name: Execute tests on Ubuntu OS
        if: matrix.os == 'ubuntu-latest'
        run: XDEBUG_MODE=coverage vendor/bin/phpunit

      - name: Execute tests on Windows OS
        if: matrix.os == 'windows-latest'
        run: vendor/bin/phpunit